import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: { padding: 44, fontFamily: 'Helvetica', fontSize: 10, color: '#1a1a1a' },
  header: { textAlign: 'center', marginBottom: 24, borderBottom: '2 solid #1a1a1a', paddingBottom: 14 },
  lodgeName: { fontSize: 18, fontWeight: 700, marginBottom: 2 },
  monthLabel: { fontSize: 12, color: '#555', marginTop: 4 },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 11, fontWeight: 700, marginBottom: 8, backgroundColor: '#f0f0f0', padding: 6 },
  eventRow: { flexDirection: 'row', paddingVertical: 5, borderBottom: '0.5 solid #ddd' },
  eventDate: { width: 90, fontWeight: 700 },
  eventTitle: { flex: 1 },
  eventLoc: { width: 140, color: '#666', fontSize: 9 },
  birthdayRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4, borderBottom: '0.5 solid #eee' },
  announcementText: { fontSize: 10, lineHeight: 1.5, marginBottom: 8 },
  empty: { fontSize: 9, color: '#999', fontStyle: 'italic', padding: 8 },
  footer: { position: 'absolute', bottom: 24, left: 44, right: 44, fontSize: 7, color: '#999', textAlign: 'center' },
})

export type TrestleboardData = {
  lodgeName: string
  lodgeNumber: string
  monthLabel: string
  meetingSchedule: string | null
  events: { title: string; date: string; time: string | null; location: string | null }[]
  birthdays: { name: string; date: string }[]
  announcement: string
  generatedAt: string
}

export function TrestleboardDocument({ data }: { data: TrestleboardData }) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.lodgeName}>{data.lodgeName} #{data.lodgeNumber}</Text>
          <Text style={styles.monthLabel}>Trestleboard — {data.monthLabel}</Text>
          {data.meetingSchedule && <Text style={{ fontSize: 9, color: '#777', marginTop: 4 }}>{data.meetingSchedule}</Text>}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>This Month's Calendar</Text>
          {data.events.length === 0 && <Text style={styles.empty}>No events scheduled this month.</Text>}
          {data.events.map((e, i) => (
            <View key={i} style={styles.eventRow}>
              <Text style={styles.eventDate}>{e.date}{e.time ? ` · ${e.time}` : ''}</Text>
              <Text style={styles.eventTitle}>{e.title}</Text>
              {e.location && <Text style={styles.eventLoc}>{e.location}</Text>}
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Birthdays This Month</Text>
          {data.birthdays.length === 0 && <Text style={styles.empty}>No birthdays on record for this month — dates of birth are optional and many members may not have theirs entered yet.</Text>}
          {data.birthdays.map((b, i) => (
            <View key={i} style={styles.birthdayRow}>
              <Text>{b.name}</Text>
              <Text style={{ color: '#666' }}>{b.date}</Text>
            </View>
          ))}
        </View>

        {data.announcement && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>From the Secretary</Text>
            <Text style={styles.announcementText}>{data.announcement}</Text>
          </View>
        )}

        <Text style={styles.footer} fixed>
          {data.lodgeName} #{data.lodgeNumber} · Generated by LodgeOS on {data.generatedAt}
        </Text>
      </Page>
    </Document>
  )
}
